### ISSUE TITLE
Some opinions which will help you

### ISSUE THREAD

**Issue by vtddggg** [akanimax/fagan#1]

**Comment by vtddggg** [comment]
Good idea！！

you generalized Self-Attention structure in GAN. From a theoretical perspective, I still have some questions. 

First, the idea is most the same as [this](https://arxiv.org/abs/1704.06904), which use encoder-decoder architecture to approximate bottom-up and top down attention. And then add attended feature maps to the inputs. (also this method can do k*k conv as you refers) The biggest difference can be the way of calculating attention (your way or SAGAN use a NLP-style attention method). 

If you try to concat instead of summing up the two outputs？ Concat maybe another interesting variant.

**Comment by akanimax** [comment]
Hi Mao Yufeng (@vtddggg), 

Thank you for your suggestions. I will refer to the paper that you shared. You are right, I am using (SAGAN uses) the attention mechanism which was defined in the ["Attention is all you need paper"](https://arxiv.org/abs/1706.03762). The mechanism creates **Q**, **K** and **V** banks from the same input and performs attention over it.

Concatenating the two outputs was indeed on my **ToTry** list. But I actually wanted to analyse the _alpha_ values of various layers on a trained network prior to trying concatenation. Precisely, if the _alpha_ values are close to ~0.5 it would mean that the network is using output from both the paths, whereby, concatenation would be more apt.

Nevertheless, Thank you so much for your suggestions. They'll definitely be helpful.
Feel free to ask more questions and / or open PRs if you get any interesting results with this layer. :+1: 
:smile: 

Cheers :beer:!
@akanimax
