### ISSUE TITLE
Value of gamma

### ISSUE THREAD

**Issue by tea1528** [akanimax/fagan#2]
Hi, thanks for an interesting project and idea.

I wanted to ask you how the gamma value changes over time.

Since it is not normalized and doesn't have constraint, there's a possibility that the value becomes smaller than zero and you wouldn't have any effect of attention I guess.

It would be greatly appreciated if you could describe how the gamma value turned out in your experiment.

**Comment by akanimax** [comment]
@tea1528,

Thank you for your compliment.
Indeed, you are right that the gamma value is not normalized and theoretically, it's possible that the values can go out of the [0-1] range. 
Practically, however, the values never exceeded 0.2 in my celebA experiments and everything is numerically stable. You can definitely wrap the gamma in in a sigmoid perhaps, for being extremely safe. 
Just modify this line of code here -> [https://github.com/akanimax/attn_gan_pytorch/blob/master/attn_gan_pytorch/CustomLayers.py#L286](https://github.com/akanimax/attn_gan_pytorch/blob/master/attn_gan_pytorch/CustomLayers.py#L286). to perform a sigmoid prior to calculating the final activations.

Hope this helps.

Thanks and regards,
@akanimax

**Comment by tea1528** [comment]
@akanimax Thanks for the detailed explanation!
